services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: true

    Zinvapel\Basis\OpenApiAssertionBundle\Command\ParseSwaggerCommand:
        tags:
            - { name: console.command, command: zinvapel:oa:parse-swagger }

    Symfony\Component\Yaml\Parser: ~