services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: true

    Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\GenerateProtoFromSchemaService:
        arguments:
            $directors:
                - '@zinvapel.open_api_assertion.proto.generate.director.request'
                - '@zinvapel.open_api_assertion.proto.generate.director.response'

    zinvapel.open_api_assertion.proto.generate.director.request:
        class: Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\Director
        arguments:
            - request
            - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\Builder'
            - '@zinvapel.open_api_assertion.proto.generate.builder.property.request'
            - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\AssertionBuilder\AssertionBuilder'

    zinvapel.open_api_assertion.proto.generate.director.response:
        class: Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\Director
        arguments:
            - request
            - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\Builder'
            - '@zinvapel.open_api_assertion.proto.generate.builder.property.response'
            - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\AssertionBuilder\AssertionBuilder'

    zinvapel.open_api_assertion.proto.generate.builder.property.request:
        class: Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\PropertyBuilder\Request

    zinvapel.open_api_assertion.proto.generate.builder.property.response:
        class: Zinvapel\Basis\OpenApiAssertionBundle\Proto\Generate\Builder\PropertyBuilder\Response
