services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: true

    Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\TransformerInterface:
        alias: Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\FirstAcceptable

    Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\FirstAcceptable:
        arguments:
            -
                - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\Collection'
                - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\Multiple'
                - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\WithOptions'
                - '@Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\Assert\Transformer\WithoutOptions'
