services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: true

    Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\ClassString\TransformProtoToClassService: ~
    Zinvapel\Basis\OpenApiAssertionBundle\Proto\Transform\ClassString\Transformer\Transformer: ~