services:
    _defaults:
        public: false
        autoconfigure: false
        autowire: true

    Zinvapel\Basis\BasisBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection'
            - '../../Resources'
            - '../../Regular/Dto'
            - '../../Regular/ServiceDecorator'
            - '../../Http/Flow'